version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: desafio
    ports:
      - "5432:5432"
    networks:
      - app-net

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://desafio:desafio@postgres:5432/desafio?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - app-net

  app-desafio:
    build: .
    container_name: app-desafio
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-desafio
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  pgdata: {}
  grafana: {}
