name: CI - Maven Build & Test

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]   # troque para ['17','21'] se quiser matriz
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Maven - Clean Verify (com testes)
        run: ./mvnw -B -DskipITs clean verify

      - name: Upload JAR (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          if-no-files-found: error

      - name: Upload Surefire Reports (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**

      - name: Upload JaCoCo (se usar cobertura)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/**
